name: Unit tests & Coverage
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3.3.0


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - run: npm i -g yarn

      - name: set up dependencies
        run: yarn install --immutable

      - name: run lint
        uses: wearerequired/lint-action@v2
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          auto_fix: true

      - name: run coverage
        run: yarn locov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
